### ISSUE TITLE
User Guide link does not go to the html page

### ISSUE THREAD

**Issue by damithc** [AY1920S2-CS2113T-M16-1/tp#145]
The UG link in your landing page goes to an .adoc page, not an html page.
Why are you using adoc anyway? If you use adoc, there are additional set up you need to do to publish asciidoc files to github pages.
Plus, our scripts only check .md files as per the tP template we gave.

**Comment by jichngan** [comment]
Hi Prof, so we have to convert both of our UG/DG to a .md file? adoc files give us an ease in numbering the columns and having the Table of Content stuff. Does it affect our DG review for later on today?

**Comment by damithc** [comment]
Probably will not affect DG review.
I can update the script to check both .md and .adoc files if you want to keep using adoc format.
Try to figure out how to auto-generate html files though, or else the pdf files you submit and the UG/DG visible on the web are not going to look nice i.e., trading off end-user experience for developer experience. If you receive bug reports in the PE regarding 'un-formatted UG/DG', you'll have to accept them.
Last semester, there were students who tried using adoc and made a mess of it. That's why we talked to CS2101 side and decided to remove the requirement to have figure/table/section numbering in UG/DG and thereby eliminated the need for asciidoc this semester.
